services:
  plant-api:
    image: ${DOCKER_USER}/plant-api:latest
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      DATABASE: ${DATABASE}
      DB_USERNAME: ${USERNAME}
      DB_PASSWORD: ${PASSWORD}
      DB_HOST: ${HOST}
    ports:
      - 80:3000